# Generated by Django 3.1.1 on 2023-06-04 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosiz', '0003_auto_20230604_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiseaseDiagnosed',
            new_name='AllDiagnosedDisease',
        ),
    ]
