# Generated by Django 3.1.1 on 2023-06-05 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosiz', '0004_auto_20230604_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllDiagnosedDisease',
            new_name='DiagnosedDisease',
        ),
    ]
