# Generated by Django 3.1.1 on 2023-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosiz', '0006_diagnoseddisease_symptoms_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnoseddisease',
            name='symptoms_selected',
        ),
    ]
