# Generated by Django 3.1.1 on 2023-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosiz', '0007_remove_diagnoseddisease_symptoms_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoseddisease',
            name='symptoms_selected',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
